import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

const border = `1px solid ${theme.colors.line}`;

export const workflowStudioStyles = {
  page: {
    minHeight: "100vh",
    width: "100%",
    background: theme.colors.surface,
    color: theme.colors.ink,
    padding: "28px 0 64px",
  } satisfies CSSProperties,
  navSection: {
    width: "100%",
    padding: "0 32px 24px",
    borderBottom: border,
  } satisfies CSSProperties,
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  logoButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: "none",
    background: "transparent",
    cursor: "pointer",
  } satisfies CSSProperties,
  logo: {
    width: "172px",
    height: "54px",
    objectFit: "contain",
    display: "block",
  } satisfies CSSProperties,
  navActions: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  backButton: {
    border: "none",
    borderRadius: "22px",
    minHeight: "56px",
    padding: "0 28px",
    background: theme.colors.coal,
    color: theme.colors.surface,
    fontSize: "0.98rem",
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  secondaryButton: {
    border,
    borderRadius: "18px",
    minHeight: "56px",
    padding: "0 20px",
    background: theme.colors.surface,
    color: theme.colors.ink,
    fontSize: "0.98rem",
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  heroSection: {
    width: "100%",
    padding: "32px 32px 0",
  } satisfies CSSProperties,
  kicker: {
    margin: "0 0 12px",
    color: theme.colors.orange,
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  title: {
    margin: 0,
    maxWidth: "760px",
    fontSize: "clamp(1.9rem, 4vw, 3.3rem)",
    lineHeight: 1.08,
    letterSpacing: "-0.03em",
    fontWeight: 600,
  } satisfies CSSProperties,
  subtitle: {
    margin: "16px 0 0",
    maxWidth: "760px",
    color: theme.colors.muted,
    fontSize: "1.05rem",
    lineHeight: 1.7,
  } satisfies CSSProperties,
  section: {
    width: "100%",
    padding: "32px 32px 0",
  } satisfies CSSProperties,
  marketplaceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "28px",
  } satisfies CSSProperties,
  marketCard: {
    display: "grid",
    alignContent: "start",
    gap: "0",
    border,
    borderRadius: "28px",
    background: theme.colors.surface,
    overflow: "hidden",
  } satisfies CSSProperties,
  imageFrame: {
    width: "100%",
    minHeight: "220px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: theme.colors.gray,
    padding: "18px",
  } satisfies CSSProperties,
  cardImage: {
    width: "100%",
    maxWidth: "200px",
    height: "auto",
    display: "block",
  } satisfies CSSProperties,
  cardBody: {
    display: "grid",
    gap: "10px",
    padding: "18px 18px 20px",
  } satisfies CSSProperties,
  marketType: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.78rem",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  marketTitle: {
    margin: 0,
    fontSize: "1.22rem",
    fontWeight: 500,
    lineHeight: 1.2,
  } satisfies CSSProperties,
  marketSummary: {
    margin: 0,
    color: theme.colors.muted,
    lineHeight: 1.6,
    fontSize: "0.93rem",
    display: "-webkit-box",
    WebkitLineClamp: 4,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
} as const;
