import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

const border = `1px solid ${theme.colors.line}`;

export const workflowStudioStyles = {
  page: {
    minHeight: "100vh",
    width: "100%",
    background: theme.colors.surface,
    color: theme.colors.ink,
    padding: "28px 0 64px",
  } satisfies CSSProperties,
  navSection: {
    width: "100%",
    padding: "0 32px 24px",
    borderBottom: border,
  } satisfies CSSProperties,
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  logoButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: "none",
    background: "transparent",
    cursor: "pointer",
  } satisfies CSSProperties,
  logo: {
    width: "172px",
    height: "54px",
    objectFit: "contain",
    display: "block",
  } satisfies CSSProperties,
  navActions: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  backButton: {
    border: "none",
    borderRadius: "22px",
    minHeight: "56px",
    padding: "0 28px",
    background: theme.colors.coal,
    color: theme.colors.surface,
    fontSize: "0.98rem",
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  secondaryButton: {
    border,
    borderRadius: "18px",
    minHeight: "56px",
    padding: "0 20px",
    background: theme.colors.surface,
    color: theme.colors.ink,
    fontSize: "0.98rem",
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  createButton: {
    border: "none",
    borderRadius: "8px",
    minHeight: "56px",
    padding: "0 22px",
    background: theme.colors.orange,
    color: theme.colors.surface,
    fontSize: "0.98rem",
    fontWeight: 700,
    cursor: "pointer",
  } satisfies CSSProperties,
  heroSection: {
    width: "100%",
    padding: "32px 32px 0",
  } satisfies CSSProperties,
  kicker: {
    margin: "0 0 12px",
    color: theme.colors.orange,
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  title: {
    margin: 0,
    maxWidth: "760px",
    fontSize: "clamp(1.9rem, 4vw, 3.3rem)",
    lineHeight: 1.08,
    letterSpacing: "-0.03em",
    fontWeight: 600,
  } satisfies CSSProperties,
  subtitle: {
    margin: "16px 0 0",
    maxWidth: "760px",
    color: theme.colors.muted,
    fontSize: "1.05rem",
    lineHeight: 1.7,
  } satisfies CSSProperties,
  heroCta: {
    marginTop: "22px",
    minHeight: "50px",
    padding: "0 20px",
    border: "none",
    borderRadius: "8px",
    background: theme.colors.orange,
    color: theme.colors.surface,
    fontWeight: 700,
    cursor: "pointer",
  } satisfies CSSProperties,
  section: {
    width: "100%",
    padding: "32px 32px 0",
  } satisfies CSSProperties,
  marketplaceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "28px",
  } satisfies CSSProperties,
  marketCard: {
    display: "flex",
    flexDirection: "column",
    border,
    borderRadius: "8px",
    background: theme.colors.surface,
    overflow: "hidden",
  } satisfies CSSProperties,
  imageFrame: {
    width: "100%",
    height: "260px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: theme.colors.gray,
    padding: "18px",
  } satisfies CSSProperties,
  cardImage: {
    width: "100%",
    maxWidth: "240px",
    maxHeight: "220px",
    height: "auto",
    display: "block",
    objectFit: "contain",
  } satisfies CSSProperties,
  cardBody: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    padding: "18px 18px 20px",
    gap: "10px",
    minHeight: 0,
  } satisfies CSSProperties,
  marketType: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.78rem",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    flexShrink: 0,
  } satisfies CSSProperties,
  marketTitle: {
    margin: 0,
    fontSize: "1.22rem",
    fontWeight: 500,
    lineHeight: 1.2,
    flexShrink: 0,
  } satisfies CSSProperties,
  marketSummary: {
    margin: 0,
    color: theme.colors.muted,
    lineHeight: 1.6,
    fontSize: "0.93rem",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    flexShrink: 0,
  } satisfies CSSProperties,
  tagRow: {
    display: "flex",
    flexWrap: "nowrap",
    gap: "6px",
    minWidth: 0,
    overflow: "hidden",
    flexShrink: 0,
    height: "24px",
    alignItems: "center",
  } satisfies CSSProperties,
  tagPill: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 8px",
    borderRadius: "5px",
    border: `1px solid rgba(21, 32, 51, 0.12)`,
    background: "transparent",
    color: theme.colors.muted,
    fontSize: "0.7rem",
    fontWeight: 600,
    letterSpacing: "0.02em",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardButton: {
    minHeight: "42px",
    border: "none",
    borderRadius: "8px",
    background: theme.colors.orange,
    color: theme.colors.surface,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,
  cardSecondaryButton: {
    minHeight: "42px",
    border,
    borderRadius: "8px",
    background: theme.colors.surface,
    color: theme.colors.ink,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,
  cardActionRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    minWidth: 0,
    marginTop: "auto",
    paddingTop: "6px",
    flexShrink: 0,
  } satisfies CSSProperties,
  statusPanel: {
    padding: "24px",
    border,
    borderRadius: "8px",
    color: theme.colors.muted,
    background: theme.colors.surface,
    lineHeight: 1.6,
  } satisfies CSSProperties,
} as const;
