import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

const border = `1px solid ${theme.colors.line}`;

export const workflowStudioStyles = {
  // ── Page shell ─────────────────────────────────────────────────────────
  page: {
    minHeight: "100vh",
    width: "100%",
    background: theme.colors.surface,
    color: theme.colors.ink,
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,

  // ── Nav bar ─────────────────────────────────────────────────────────────
  nav: {
    display: "flex",
    alignItems: "center",
    padding: "0 36px",
    height: "68px",
    flexShrink: 0,
    background: "#ffffff",
    borderBottom: border,
    gap: "20px",
  } satisfies CSSProperties,
  logoButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  logo: {
    width: "130px",
    height: "44px",
    objectFit: "contain",
    display: "block",
  } satisfies CSSProperties,
  navCenter: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
  } satisfies CSSProperties,
  navTitle: {
    fontSize: "1rem",
    fontWeight: 700,
    color: theme.colors.ink,
    letterSpacing: "-0.01em",
  } satisfies CSSProperties,
  navCount: {
    fontSize: "0.8rem",
    fontWeight: 700,
    color: theme.colors.muted,
    background: theme.colors.gray,
    padding: "3px 11px",
    borderRadius: "999px",
  } satisfies CSSProperties,
  navActions: {
    display: "flex",
    gap: "10px",
    flexShrink: 0,
  } satisfies CSSProperties,
  backButton: {
    border,
    borderRadius: "12px",
    minHeight: "42px",
    padding: "0 18px",
    background: "#ffffff",
    color: theme.colors.ink,
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  createButton: {
    border: "none",
    borderRadius: "12px",
    minHeight: "42px",
    padding: "0 20px",
    background: theme.colors.orange,
    color: "#ffffff",
    fontSize: "0.9rem",
    fontWeight: 700,
    cursor: "pointer",
  } satisfies CSSProperties,

  // ── Catalog section ─────────────────────────────────────────────────────
  section: {
    flex: 1,
    padding: "36px 36px 72px",
  } satisfies CSSProperties,

  // ── Empty state ─────────────────────────────────────────────────────────
  emptyPanel: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "100px 24px",
    textAlign: "center",
  } satisfies CSSProperties,
  emptyTitle: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  emptyText: {
    margin: "10px 0 0",
    color: theme.colors.muted,
    fontSize: "0.95rem",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  emptyCta: {
    marginTop: "22px",
    minHeight: "48px",
    padding: "0 24px",
    border: "none",
    borderRadius: "14px",
    background: theme.colors.orange,
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.95rem",
  } satisfies CSSProperties,

  // ── Status ─────────────────────────────────────────────────────────────
  statusPanel: {
    padding: "28px",
    borderRadius: "16px",
    border,
    color: theme.colors.muted,
    background: "#ffffff",
    lineHeight: 1.6,
    fontSize: "0.95rem",
  } satisfies CSSProperties,

  // ── Marketplace grid ────────────────────────────────────────────────────
  marketplaceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "24px",
  } satisfies CSSProperties,

  // ── Card ────────────────────────────────────────────────────────────────
  marketCard: {
    display: "flex",
    flexDirection: "column",
    border,
    borderRadius: "8px",
    background: "#ffffff",
    overflow: "hidden",
  } satisfies CSSProperties,
  imageFrame: {
    width: "100%",
    height: "260px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: theme.colors.gray,
    padding: "18px",
  } satisfies CSSProperties,
  cardImage: {
    width: "100%",
    maxWidth: "240px",
    maxHeight: "220px",
    height: "auto",
    display: "block",
    objectFit: "contain",
  } satisfies CSSProperties,
  cardBody: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    padding: "20px 22px 22px",
    gap: "10px",
    minHeight: 0,
  } satisfies CSSProperties,
  marketType: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.75rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    flexShrink: 0,
  } satisfies CSSProperties,
  marketTitle: {
    margin: 0,
    fontSize: "1.22rem",
    fontWeight: 500,
    lineHeight: 1.2,
    flexShrink: 0,
  } satisfies CSSProperties,
  marketSummary: {
    margin: 0,
    color: theme.colors.muted,
    lineHeight: 1.6,
    fontSize: "0.9rem",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    flexShrink: 0,
  } satisfies CSSProperties,
  tagRow: {
    display: "flex",
    flexWrap: "nowrap",
    gap: "6px",
    minWidth: 0,
    overflow: "hidden",
    flexShrink: 0,
    height: "24px",
    alignItems: "center",
  } satisfies CSSProperties,
  tagPill: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 9px",
    borderRadius: "6px",
    border: `1px solid rgba(21, 32, 51, 0.11)`,
    background: "transparent",
    color: theme.colors.muted,
    fontSize: "0.7rem",
    fontWeight: 600,
    letterSpacing: "0.02em",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardActionRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginTop: "auto",
    paddingTop: "4px",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardButton: {
    minHeight: "42px",
    border: "none",
    borderRadius: "8px",
    background: theme.colors.orange,
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,
  cardSecondaryButton: {
    minHeight: "42px",
    border,
    borderRadius: "8px",
    background: "#ffffff",
    color: theme.colors.ink,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,
} as const;
