import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

const border = `1px solid ${theme.colors.line}`;

export const workflowCreationStyles = {
  page: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "320px minmax(0, 1fr)",
    background: theme.colors.surface,
  } satisfies CSSProperties,
  sidebar: {
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    gap: "18px",
    padding: "20px",
    borderRight: border,
    background: theme.colors.surface,
    height: "100vh",
    overflow: "hidden",
  } satisfies CSSProperties,
  sidebarCollapsed: {
    display: "grid",
    gridTemplateRows: "auto auto",
    gap: "18px",
    padding: "20px 12px",
    borderRight: border,
    background: theme.colors.surface,
    width: "88px",
    height: "100vh",
    overflow: "hidden",
  } satisfies CSSProperties,
  sidebarTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  } satisfies CSSProperties,
  sidebarTitle: {
    margin: 0,
    fontSize: "1.05rem",
    fontWeight: 500,
    color: theme.colors.ink,
  } satisfies CSSProperties,
  collapseButton: {
    width: "36px",
    height: "36px",
    borderRadius: "12px",
    border,
    background: theme.colors.surface,
    color: theme.colors.ink,
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  domainTabs: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
  } satisfies CSSProperties,
  domainTab: {
    minHeight: "42px",
    borderRadius: "14px",
    border,
    background: theme.colors.surface,
    color: theme.colors.ink,
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  domainTabActive: {
    minHeight: "42px",
    borderRadius: "14px",
    border: `1px solid ${theme.colors.orange}`,
    background: theme.colors.orange,
    color: theme.colors.surface,
    fontWeight: 500,
    cursor: "pointer",
  } satisfies CSSProperties,
  sidebarBody: {
    overflowY: "auto",
    paddingRight: "4px",
    display: "grid",
    gap: "18px",
  } satisfies CSSProperties,
  stageSection: {
    display: "grid",
    gap: "10px",
  } satisfies CSSProperties,
  stageLabel: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.76rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  toolList: {
    display: "grid",
    gap: "10px",
  } satisfies CSSProperties,
  toolCard: {
    width: "100%",
    textAlign: "left",
    padding: "14px",
    borderRadius: "16px",
    border,
    background: theme.colors.surface,
    cursor: "grab",
  } satisfies CSSProperties,
  toolTitle: {
    color: theme.colors.ink,
    fontWeight: 500,
    fontSize: "0.96rem",
  } satisfies CSSProperties,
  toolName: {
    marginTop: "6px",
    color: theme.colors.muted,
    fontSize: "0.82rem",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  canvasArea: {
    position: "relative",
    minHeight: "100vh",
    overflow: "hidden",
    background: theme.colors.gray,
  } satisfies CSSProperties,
  canvasGrid: {
    position: "absolute",
    inset: 0,
    backgroundImage:
      "linear-gradient(rgba(21, 32, 51, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(21, 32, 51, 0.06) 1px, transparent 1px)",
    backgroundSize: "28px 28px",
    pointerEvents: "none",
  } satisfies CSSProperties,
  canvasToolbar: {
    position: "absolute",
    top: "20px",
    left: "20px",
    right: "20px",
    zIndex: 3,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "12px",
    alignItems: "start",
  } satisfies CSSProperties,
  promptInput: {
    minHeight: "78px",
    borderRadius: "18px",
    border,
    background: theme.colors.surface,
    color: theme.colors.ink,
    padding: "16px 18px",
    resize: "none",
    lineHeight: 1.6,
    fontSize: "1rem",
    outline: "none",
  } satisfies CSSProperties,
  generateButton: {
    minHeight: "78px",
    padding: "0 22px",
    borderRadius: "18px",
    border: "none",
    background: theme.colors.orange,
    color: theme.colors.surface,
    fontWeight: 500,
    fontSize: "0.98rem",
    cursor: "pointer",
  } satisfies CSSProperties,
  draftingBadge: {
    position: "absolute",
    top: "118px",
    left: "20px",
    zIndex: 3,
    display: "inline-flex",
    alignItems: "center",
    minHeight: "38px",
    padding: "0 14px",
    borderRadius: "999px",
    background: theme.colors.surface,
    border,
    color: theme.colors.orange,
    fontSize: "0.9rem",
    fontWeight: 500,
  } satisfies CSSProperties,
  emptyState: {
    position: "absolute",
    inset: "0",
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    padding: "120px 24px 24px",
    zIndex: 1,
  } satisfies CSSProperties,
  emptyTitle: {
    margin: 0,
    fontSize: "1.35rem",
    fontWeight: 500,
    color: theme.colors.ink,
  } satisfies CSSProperties,
  emptyText: {
    margin: "10px auto 0",
    maxWidth: "520px",
    color: theme.colors.muted,
    lineHeight: 1.7,
  } satisfies CSSProperties,
  canvasNode: {
    position: "absolute",
    zIndex: 2,
    width: "180px",
    minHeight: "112px",
    borderRadius: "18px",
    border,
    background: theme.colors.surface,
    padding: "14px",
    cursor: "grab",
    userSelect: "none",
  } satisfies CSSProperties,
  canvasNodeActive: {
    position: "absolute",
    zIndex: 2,
    width: "180px",
    minHeight: "112px",
    borderRadius: "18px",
    border: `1px solid ${theme.colors.orange}`,
    background: theme.colors.surface,
    padding: "14px",
    cursor: "grab",
    userSelect: "none",
  } satisfies CSSProperties,
  nodeStage: {
    color: theme.colors.orange,
    fontSize: "0.72rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  nodeTitle: {
    marginTop: "8px",
    color: theme.colors.ink,
    fontSize: "0.98rem",
    fontWeight: 500,
    lineHeight: 1.35,
  } satisfies CSSProperties,
  nodeTool: {
    marginTop: "6px",
    color: theme.colors.muted,
    fontSize: "0.8rem",
  } satisfies CSSProperties,
  nodeStateDraft: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    marginTop: "10px",
    padding: "0 10px",
    borderRadius: "999px",
    background: theme.colors.gray,
    color: theme.colors.muted,
    fontSize: "0.8rem",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  nodeStateRunning: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    marginTop: "10px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#fff1e7",
    color: theme.colors.orange,
    fontSize: "0.8rem",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  nodeStateDone: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    marginTop: "10px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#eef8f1",
    color: "#2e8b57",
    fontSize: "0.8rem",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  nodeStateWaiting: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    marginTop: "10px",
    padding: "0 10px",
    borderRadius: "999px",
    background: theme.colors.coal,
    color: theme.colors.surface,
    fontSize: "0.8rem",
    textTransform: "capitalize",
  } satisfies CSSProperties,
  connector: {
    position: "absolute",
    top: "50%",
    right: "-72px",
    width: "60px",
    height: "1px",
    background: "rgba(21, 32, 51, 0.18)",
  } satisfies CSSProperties,
  selectionPanel: {
    position: "absolute",
    right: "20px",
    bottom: "20px",
    zIndex: 3,
    width: "240px",
    padding: "18px",
    borderRadius: "18px",
    border,
    background: theme.colors.surface,
  } satisfies CSSProperties,
  selectionLabel: {
    color: theme.colors.orange,
    fontSize: "0.76rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  selectionTitle: {
    marginTop: "8px",
    color: theme.colors.ink,
    fontSize: "1rem",
    fontWeight: 500,
  } satisfies CSSProperties,
  selectionMeta: {
    marginTop: "6px",
    color: theme.colors.muted,
    fontSize: "0.86rem",
  } satisfies CSSProperties,
} as const;
