import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

const border = `1px solid ${theme.colors.line}`;

export const workflowCreationStyles = {
  page: {
    height: "100vh",
    display: "grid",
    overflow: "hidden",
    background: "#fffaf6",
    color: theme.colors.ink,
  } satisfies CSSProperties,
  sidebar: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "20px",
    padding: "24px 20px",
    borderRight: border,
    background: "#fffdfb",
    minHeight: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  sidebarCompact: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "16px",
    padding: "20px 20px 16px",
    borderBottom: border,
    background: "#fffdfb",
    minHeight: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  sidebarScrollArea: {
    minHeight: 0,
    overflowY: "auto",
    display: "grid",
    alignContent: "start",
    gap: "18px",
    paddingRight: "10px",
  } satisfies CSSProperties,
  sidebarTopRow: {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
  } satisfies CSSProperties,
  sidebarTitleBlock: {
    minWidth: 0,
    flex: 1,
  } satisfies CSSProperties,
  sidebarActions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    justifyContent: "end",
  } satisfies CSSProperties,
  sidebarEyebrow: {
    margin: "0 0 8px",
    color: theme.colors.orange,
    fontSize: "0.75rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  sidebarTitle: {
    margin: 0,
    maxWidth: "12ch",
    fontSize: "clamp(1.45rem, 2vw, 2rem)",
    lineHeight: 1.06,
    letterSpacing: "-0.03em",
    fontWeight: 700,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  secondaryIconButton: {
    minHeight: "40px",
    padding: "0 14px",
    borderRadius: "14px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  briefCard: {
    display: "grid",
    gap: "16px",
    padding: "18px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    minWidth: 0,
  } satisfies CSSProperties,
  sectionHeader: {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
  } satisfies CSSProperties,
  sectionEyebrow: {
    margin: "0 0 6px",
    color: theme.colors.orange,
    fontSize: "0.74rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  sectionTitle: {
    margin: 0,
    fontSize: "1.08rem",
    fontWeight: 600,
    lineHeight: 1.2,
  } satisfies CSSProperties,
  domainTabs: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(0, 1fr))",
    gap: "10px",
    minWidth: 0,
  } satisfies CSSProperties,
  domainTab: {
    display: "grid",
    gap: "6px",
    textAlign: "left",
    padding: "14px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    cursor: "pointer",
    minWidth: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  domainTabActive: {
    display: "grid",
    gap: "6px",
    textAlign: "left",
    padding: "14px",
    borderRadius: "8px",
    border: `1px solid ${theme.colors.orange}`,
    background: theme.colors.orange,
    color: "#ffffff",
    cursor: "pointer",
    minWidth: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  domainTabTitle: {
    fontSize: "0.98rem",
    fontWeight: 700,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  domainTabCopy: {
    fontSize: "0.8rem",
    lineHeight: 1.45,
    opacity: 0.84,
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  domainSummaryCard: {
    display: "grid",
    gap: "14px",
    padding: "16px",
    borderRadius: "8px",
    background: "#fff7f2",
    border: "1px solid rgba(255,82,0,0.1)",
  } satisfies CSSProperties,
  domainSummaryTitle: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  domainSummaryText: {
    margin: "6px 0 0",
    color: theme.colors.muted,
    fontSize: "0.92rem",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  domainSummaryMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    minWidth: 0,
  } satisfies CSSProperties,
  metaPill: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "32px",
    padding: "0 12px",
    borderRadius: theme.radius.pill,
    background: "#ffffff",
    color: theme.colors.ink,
    fontSize: "0.82rem",
    fontWeight: 600,
    lineHeight: 1.25,
    maxWidth: "100%",
    whiteSpace: "normal",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  promptLabel: {
    color: theme.colors.ink,
    fontSize: "0.9rem",
    fontWeight: 600,
  } satisfies CSSProperties,
  promptInput: {
    minHeight: "148px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "18px",
    resize: "vertical",
    lineHeight: 1.7,
    fontSize: "0.98rem",
    outline: "none",
  } satisfies CSSProperties,
  selectInput: {
    minHeight: "46px",
    width: "100%",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "0 14px",
    outline: "none",
  } satisfies CSSProperties,
  textInput: {
    minHeight: "42px",
    width: "100%",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "0 12px",
    outline: "none",
    minWidth: 0,
  } satisfies CSSProperties,
  compactTextarea: {
    width: "100%",
    minHeight: "76px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "12px",
    resize: "vertical",
    lineHeight: 1.5,
    fontSize: "0.86rem",
    outline: "none",
  } satisfies CSSProperties,
  inputGrid: {
    display: "grid",
    gap: "14px",
  } satisfies CSSProperties,
  fieldBlock: {
    display: "grid",
    gap: "8px",
    minWidth: 0,
  } satisfies CSSProperties,
  fieldHelp: {
    color: theme.colors.muted,
    fontSize: "0.82rem",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  suggestionRail: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    minWidth: 0,
  } satisfies CSSProperties,
  suggestionChip: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px 14px",
    borderRadius: "8px",
    border,
    background: "#fff8f2",
    color: theme.colors.ink,
    fontSize: "0.84rem",
    lineHeight: 1.4,
    textAlign: "center",
    maxWidth: "100%",
    whiteSpace: "normal",
    overflowWrap: "anywhere",
    cursor: "pointer",
  } satisfies CSSProperties,
  canvasArea: {
    position: "relative",
    minHeight: 0,
    overflow: "hidden",
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    gap: "20px",
    background: "#fff8f2",
    padding: "32px",
  } satisfies CSSProperties,
  canvasBackdrop: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(180deg, rgba(255, 82, 0, 0.05) 0%, rgba(255, 82, 0, 0) 40%)",
    pointerEvents: "none",
  } satisfies CSSProperties,
  canvasHeader: {
    position: "relative",
    zIndex: 2,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "20px",
    alignItems: "end",
  } satisfies CSSProperties,
  canvasHeaderCopy: {
    display: "grid",
    gap: "10px",
    maxWidth: "820px",
  } satisfies CSSProperties,
  canvasEyebrow: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.76rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  canvasTitle: {
    margin: 0,
    fontSize: "clamp(1.55rem, 2.8vw, 2.5rem)",
    lineHeight: 1.06,
    letterSpacing: "-0.03em",
    fontWeight: 700,
  } satisfies CSSProperties,
  canvasSubtitle: {
    margin: 0,
    color: theme.colors.muted,
    lineHeight: 1.75,
    fontSize: "1rem",
    maxWidth: "64ch",
  } satisfies CSSProperties,
  canvasHeaderActions: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
    justifyContent: "end",
  } satisfies CSSProperties,
  canvasSecondaryButton: {
    minHeight: "54px",
    padding: "0 18px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  generateButton: {
    minHeight: "54px",
    padding: "0 22px",
    borderRadius: "8px",
    border: "none",
    background: theme.colors.orange,
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  } satisfies CSSProperties,
  canvasMetaBar: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    minWidth: 0,
  } satisfies CSSProperties,
  canvasMetaPill: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "34px",
    padding: "0 14px",
    borderRadius: theme.radius.pill,
    background: "#ffffff",
    border,
    color: theme.colors.ink,
    fontSize: "0.84rem",
    fontWeight: 600,
    lineHeight: 1.25,
    maxWidth: "100%",
    whiteSpace: "normal",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  workspaceLayout: {
    position: "relative",
    zIndex: 2,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 300px",
    gap: "28px",
    alignItems: "start",
  } satisfies CSSProperties,
  flowColumn: {
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    gap: "18px",
  } satisfies CSSProperties,
  guardrailStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "12px",
  } satisfies CSSProperties,
  guardrailTile: {
    display: "grid",
    gap: "8px",
    padding: "16px 18px",
    borderRadius: "8px",
    background: "#ffffff",
    border,
  } satisfies CSSProperties,
  guardrailLabel: {
    margin: 0,
    color: theme.colors.muted,
    fontSize: "0.8rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  } satisfies CSSProperties,
  guardrailValue: {
    margin: 0,
    fontSize: "0.95rem",
    fontWeight: 600,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  flowShell: {
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    minHeight: 0,
    borderRadius: "8px",
    border,
    background: "rgba(255,255,255,0.88)",
    overflow: "hidden",
  } satisfies CSSProperties,
  flowShellHeader: {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "16px",
    padding: "22px 24px 0",
  } satisfies CSSProperties,
  flowShellEyebrow: {
    margin: "0 0 6px",
    color: theme.colors.orange,
    fontSize: "0.74rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  flowShellTitle: {
    margin: 0,
    fontSize: "1.14rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  flowStatusBadge: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "36px",
    padding: "0 14px",
    borderRadius: theme.radius.pill,
    background: "#fff7f2",
    color: theme.colors.orange,
    border,
    fontSize: "0.82rem",
    fontWeight: 600,
    textAlign: "center",
    maxWidth: "360px",
    whiteSpace: "normal",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  flowStatusBadgeMuted: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "36px",
    padding: "0 14px",
    borderRadius: theme.radius.pill,
    background: "#ffffff",
    color: theme.colors.muted,
    border,
    fontSize: "0.82rem",
    fontWeight: 600,
    textAlign: "center",
    maxWidth: "360px",
    whiteSpace: "normal",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  flowViewport: {
    position: "relative",
    minHeight: 0,
    height: "100%",
    padding: "18px 20px 24px",
  } satisfies CSSProperties,
  reactFlow: {
    width: "100%",
    height: "100%",
    minHeight: "640px",
    background: "transparent",
  } satisfies CSSProperties,
  flowControls: {
    border: "none",
    boxShadow: "none",
  } satisfies CSSProperties,
  flowHandle: {
    width: "10px",
    height: "10px",
    borderRadius: "999px",
    border: "2px solid #ffffff",
    background: theme.colors.orange,
  } satisfies CSSProperties,
  flowNodeCard: {
    width: "264px",
    minHeight: "148px",
    padding: "18px",
    borderRadius: "8px",
    border: `1px solid ${theme.colors.line}`,
    background: "#ffffff",
  } satisfies CSSProperties,
  flowNodeCardActive: {
    width: "264px",
    minHeight: "148px",
    padding: "18px",
    borderRadius: "8px",
    border: `1px solid ${theme.colors.orange}`,
    background: "#ffffff",
  } satisfies CSSProperties,
  flowNodeTopRow: {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
  } satisfies CSSProperties,
  flowNodeStage: {
    color: theme.colors.orange,
    fontSize: "0.74rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  flowNodeTitle: {
    marginTop: "16px",
    color: theme.colors.ink,
    fontSize: "1.08rem",
    fontWeight: 700,
    lineHeight: 1.32,
  } satisfies CSSProperties,
  flowNodeTool: {
    marginTop: "10px",
    color: theme.colors.muted,
    fontSize: "0.86rem",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  nodeStateDraft: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#f3f0eb",
    color: theme.colors.muted,
    fontSize: "0.74rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateRunning: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#fff0e5",
    color: theme.colors.orange,
    fontSize: "0.74rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateDone: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#eaf7ef",
    color: "#2d8c5c",
    fontSize: "0.74rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateWaiting: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#151a24",
    color: "#ffffff",
    fontSize: "0.74rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateFailed: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#fee8e8",
    color: "#b42318",
    fontSize: "0.74rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateBlocked: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "28px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#f3f0eb",
    color: "#7a5c00",
    fontSize: "0.74rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  emptyState: {
    position: "absolute",
    inset: 0,
    display: "grid",
    placeItems: "center",
    padding: "32px",
    zIndex: 1,
    pointerEvents: "none",
  } satisfies CSSProperties,
  emptyCard: {
    maxWidth: "640px",
    padding: "38px 40px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    textAlign: "center",
  } satisfies CSSProperties,
  emptyKicker: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.78rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  emptyTitle: {
    margin: "14px 0 0",
    fontSize: "1.6rem",
    lineHeight: 1.2,
    fontWeight: 700,
  } satisfies CSSProperties,
  emptyText: {
    margin: "12px auto 0",
    maxWidth: "56ch",
    color: theme.colors.muted,
    lineHeight: 1.75,
  } satisfies CSSProperties,
  inspectorRail: {
    display: "grid",
    gap: "16px",
    alignContent: "start",
  } satisfies CSSProperties,
  inspectorSection: {
    display: "grid",
    gap: "12px",
    padding: "20px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
  } satisfies CSSProperties,
  inspectorEyebrow: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.75rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  inspectorTitle: {
    margin: 0,
    fontSize: "1.08rem",
    lineHeight: 1.3,
    fontWeight: 700,
  } satisfies CSSProperties,
  inspectorText: {
    margin: 0,
    color: theme.colors.muted,
    fontSize: "0.9rem",
    lineHeight: 1.65,
  } satisfies CSSProperties,
  progressMetric: {
    display: "flex",
    alignItems: "end",
    gap: "10px",
  } satisfies CSSProperties,
  progressValue: {
    fontSize: "2rem",
    lineHeight: 1,
    fontWeight: 700,
  } satisfies CSSProperties,
  progressLabel: {
    color: theme.colors.muted,
    fontSize: "0.86rem",
    paddingBottom: "4px",
  } satisfies CSSProperties,
  selectedMetaList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  } satisfies CSSProperties,
  selectedMetaChip: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "30px",
    padding: "0 12px",
    borderRadius: "999px",
    background: "#fff7f2",
    color: theme.colors.ink,
    fontSize: "0.8rem",
    fontWeight: 600,
  } satisfies CSSProperties,
  approvalActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  } satisfies CSSProperties,
  metadataList: {
    display: "grid",
    gap: "16px",
    minWidth: 0,
  } satisfies CSSProperties,
  metadataGroup: {
    display: "grid",
    gap: "10px",
    minWidth: 0,
  } satisfies CSSProperties,
  metadataGroupTitle: {
    margin: 0,
    color: theme.colors.ink,
    fontSize: "0.9rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  metadataItem: {
    display: "grid",
    gap: "8px",
    padding: "12px",
    border,
    borderRadius: "8px",
    background: "#fffdfb",
    minWidth: 0,
  } satisfies CSSProperties,
  checkboxRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: theme.colors.muted,
    fontSize: "0.84rem",
    fontWeight: 600,
  } satisfies CSSProperties,
} as const;
