import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

const border = `1px solid ${theme.colors.line}`;

export const workflowCreationStyles = {
  // ── Page shell ─────────────────────────────────────────────────────────
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
    background: theme.colors.surface,
    color: theme.colors.ink,
  } satisfies CSSProperties,

  // ── Top bar — exact same tokens as WorkflowStudio nav ─────────────────
  topBar: {
    display: "flex",
    alignItems: "center",
    padding: "0 36px",
    height: "68px",
    flexShrink: 0,
    background: "#ffffff",
    borderBottom: border,
    gap: "20px",
  } satisfies CSSProperties,
  logoButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  logo: {
    width: "130px",
    height: "44px",
    objectFit: "contain",
    display: "block",
  } satisfies CSSProperties,
  topBarBack: {
    border,
    borderRadius: "12px",
    minHeight: "42px",
    padding: "0 18px",
    background: "#ffffff",
    color: theme.colors.ink,
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  topBarCenter: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  topBarMode: {
    fontSize: "0.9rem",
    fontWeight: 700,
    color: theme.colors.ink,
    letterSpacing: "-0.01em",
    flexShrink: 0,
  } satisfies CSSProperties,
  topBarSep: {
    color: theme.colors.soft,
    flexShrink: 0,
  } satisfies CSSProperties,
  topBarName: {
    color: theme.colors.muted,
    fontSize: "0.9rem",
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  topBarActions: {
    display: "flex",
    gap: "10px",
    flexShrink: 0,
  } satisfies CSSProperties,
  topBarPrimary: {
    border: "none",
    borderRadius: "12px",
    minHeight: "42px",
    padding: "0 20px",
    background: theme.colors.orange,
    color: "#ffffff",
    fontSize: "0.9rem",
    fontWeight: 700,
    cursor: "pointer",
  } satisfies CSSProperties,
  topBarSecondary: {
    border,
    borderRadius: "12px",
    minHeight: "42px",
    padding: "0 18px",
    background: "#ffffff",
    color: theme.colors.ink,
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,

  // ── Canvas area ────────────────────────────────────────────────────────
  canvasArea: {
    flex: 1,
    minHeight: 0,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    padding: "24px 36px 28px",
    gap: "14px",
    background: theme.colors.gray,
  } satisfies CSSProperties,
  canvasBackdrop: {
    display: "none",
  } satisfies CSSProperties,
  canvasMetaBar: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    flexShrink: 0,
  } satisfies CSSProperties,
  canvasMetaPill: {
    display: "inline-flex",
    alignItems: "center",
    height: "30px",
    padding: "0 12px",
    borderRadius: "999px",
    background: "#ffffff",
    border,
    color: theme.colors.muted,
    fontSize: "0.8rem",
    fontWeight: 600,
  } satisfies CSSProperties,
  canvasMetaPillAlert: {
    display: "inline-flex",
    alignItems: "center",
    height: "30px",
    padding: "0 12px",
    borderRadius: "999px",
    background: "#ffffff",
    border: `1px solid ${theme.colors.orange}`,
    color: theme.colors.orange,
    fontSize: "0.8rem",
    fontWeight: 700,
  } satisfies CSSProperties,

  // ── Guardrail strip ────────────────────────────────────────────────────
  guardrailStrip: {
    position: "relative",
    zIndex: 2,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "10px",
    flexShrink: 0,
  } satisfies CSSProperties,
  guardrailTile: {
    display: "grid",
    gap: "4px",
    padding: "12px 16px",
    borderRadius: "8px",
    background: "#ffffff",
    border,
  } satisfies CSSProperties,
  guardrailLabel: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  guardrailValue: {
    margin: 0,
    fontSize: "0.9rem",
    fontWeight: 600,
    lineHeight: 1.35,
    color: theme.colors.ink,
  } satisfies CSSProperties,

  // ── Flow container ─────────────────────────────────────────────────────
  flowContainer: {
    position: "relative",
    flex: 1,
    minHeight: 0,
    borderRadius: "8px",
    border,
    background: "#ffffff",
    overflow: "hidden",
    zIndex: 2,
  } satisfies CSSProperties,
  reactFlow: {
    width: "100%",
    height: "100%",
    minHeight: "500px",
    background: "transparent",
  } satisfies CSSProperties,
  flowControls: {
    border: "none",
    boxShadow: "none",
  } satisfies CSSProperties,

  // ── Flow node styles ───────────────────────────────────────────────────
  flowHandle: {
    width: "10px",
    height: "10px",
    borderRadius: "999px",
    border: "2px solid #ffffff",
    background: theme.colors.orange,
  } satisfies CSSProperties,
  flowNodeCard: {
    width: "264px",
    minHeight: "148px",
    padding: "18px",
    borderRadius: "8px",
    border: `1px solid ${theme.colors.line}`,
    background: "#ffffff",
  } satisfies CSSProperties,
  flowNodeCardActive: {
    width: "264px",
    minHeight: "148px",
    padding: "18px",
    borderRadius: "8px",
    border: `2px solid ${theme.colors.orange}`,
    background: "#ffffff",
  } satisfies CSSProperties,
  flowNodeTopRow: {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
  } satisfies CSSProperties,
  flowNodeStage: {
    color: theme.colors.orange,
    fontSize: "0.72rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  } satisfies CSSProperties,
  flowNodeTitle: {
    marginTop: "14px",
    color: theme.colors.ink,
    fontSize: "1.05rem",
    fontWeight: 700,
    lineHeight: 1.3,
    letterSpacing: "-0.01em",
  } satisfies CSSProperties,
  flowNodeTool: {
    marginTop: "8px",
    color: theme.colors.muted,
    fontSize: "0.84rem",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  nodeStateDraft: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 10px",
    borderRadius: "999px",
    background: theme.colors.gray,
    color: theme.colors.muted,
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateRunning: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#fff0e5",
    color: theme.colors.orange,
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateDone: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#eaf7ef",
    color: "#2d8c5c",
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateWaiting: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 10px",
    borderRadius: "999px",
    background: theme.colors.ink,
    color: "#ffffff",
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateFailed: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 10px",
    borderRadius: "999px",
    background: "#fee8e8",
    color: "#b42318",
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  nodeStateBlocked: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 10px",
    borderRadius: "999px",
    background: theme.colors.gray,
    color: "#7a5c00",
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,

  // ── Empty state ────────────────────────────────────────────────────────
  emptyState: {
    position: "absolute",
    inset: 0,
    display: "grid",
    placeItems: "center",
    padding: "32px",
    zIndex: 1,
    pointerEvents: "none",
  } satisfies CSSProperties,
  emptyCard: {
    maxWidth: "480px",
    padding: "40px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    textAlign: "center",
    pointerEvents: "all",
  } satisfies CSSProperties,
  emptyKicker: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.74rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.09em",
  } satisfies CSSProperties,
  emptyTitle: {
    margin: "12px 0 0",
    fontSize: "1.4rem",
    lineHeight: 1.2,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  emptyText: {
    margin: "10px auto 0",
    maxWidth: "44ch",
    color: theme.colors.muted,
    lineHeight: 1.7,
    fontSize: "0.9rem",
  } satisfies CSSProperties,
  emptyAction: {
    marginTop: "20px",
    minHeight: "42px",
    padding: "0 20px",
    borderRadius: "12px",
    border: "none",
    background: theme.colors.orange,
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,

  // ── Run progress badge ─────────────────────────────────────────────────
  runProgressBadge: {
    position: "absolute",
    top: "16px",
    right: "16px",
    zIndex: 5,
    display: "inline-flex",
    alignItems: "center",
    height: "30px",
    padding: "0 12px",
    borderRadius: "999px",
    background: "#ffffff",
    border,
    color: theme.colors.muted,
    fontSize: "0.8rem",
    fontWeight: 600,
  } satisfies CSSProperties,

  // ── Floating step inspector ────────────────────────────────────────────
  floatingInspector: {
    position: "absolute",
    bottom: "20px",
    right: "20px",
    width: "260px",
    background: "#ffffff",
    borderRadius: "8px",
    border,
    padding: "16px 18px 18px",
    zIndex: 10,
  } satisfies CSSProperties,
  floatingInspectorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "10px",
  } satisfies CSSProperties,
  inspectorCloseBtn: {
    width: "26px",
    height: "26px",
    borderRadius: "6px",
    border,
    background: "#ffffff",
    color: theme.colors.muted,
    cursor: "pointer",
    fontSize: "0.8rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
  inspectorEyebrow: {
    margin: 0,
    color: theme.colors.orange,
    fontSize: "0.7rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.09em",
  } satisfies CSSProperties,
  inspectorTitle: {
    margin: "0 0 6px",
    fontSize: "0.96rem",
    lineHeight: 1.3,
    fontWeight: 700,
    letterSpacing: "-0.01em",
  } satisfies CSSProperties,
  inspectorText: {
    margin: 0,
    color: theme.colors.muted,
    fontSize: "0.84rem",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  selectedMetaList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginTop: "10px",
  } satisfies CSSProperties,
  selectedMetaChip: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 9px",
    borderRadius: "6px",
    border: `1px solid rgba(21, 32, 51, 0.11)`,
    background: "transparent",
    color: theme.colors.muted,
    fontSize: "0.72rem",
    fontWeight: 600,
  } satisfies CSSProperties,

  // ── Modal ──────────────────────────────────────────────────────────────
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(21, 32, 51, 0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: "24px",
  } satisfies CSSProperties,
  modalDialog: {
    background: "#ffffff",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "660px",
    overflow: "hidden",
    boxShadow: theme.shadows.card,
  } satisfies CSSProperties,
  modalDialogWide: {
    background: "#ffffff",
    borderRadius: "12px",
    width: "100%",
    maxWidth: "820px",
    overflow: "hidden",
    boxShadow: theme.shadows.card,
  } satisfies CSSProperties,
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "20px 24px 18px",
    borderBottom: border,
  } satisfies CSSProperties,
  modalKicker: {
    margin: "0 0 3px",
    color: theme.colors.orange,
    fontSize: "0.68rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  } satisfies CSSProperties,
  modalTitleGroup: {
    minWidth: 0,
    flex: 1,
  } satisfies CSSProperties,
  modalTitle: {
    margin: 0,
    fontSize: "1.15rem",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: theme.colors.ink,
  } satisfies CSSProperties,
  modalClose: {
    width: "30px",
    height: "30px",
    borderRadius: "6px",
    border,
    background: "#ffffff",
    color: theme.colors.muted,
    cursor: "pointer",
    fontSize: "0.85rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  modalBody: {
    display: "flex",
    flexDirection: "row",
    minHeight: 0,
  } satisfies CSSProperties,
  // Orange-branded left panel (describe modal)
  modalPanelOrange: {
    width: "210px",
    flexShrink: 0,
    padding: "24px 20px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    background: theme.colors.orange,
    borderRight: "1px solid rgba(255,82,0,0.2)",
  } satisfies CSSProperties,
  // Neutral left info panel
  modalPanelLeft: {
    width: "240px",
    flexShrink: 0,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    background: theme.colors.gray,
    borderRight: border,
  } satisfies CSSProperties,
  // Right form panel
  modalPanelRight: {
    flex: 1,
    padding: "20px 22px",
    display: "grid",
    alignContent: "start",
    gap: "14px",
    minWidth: 0,
  } satisfies CSSProperties,
  // Single-column panel for simple modals (approval)
  modalPanelSingle: {
    flex: 1,
    padding: "20px 24px",
    display: "grid",
    alignContent: "start",
    gap: "14px",
  } satisfies CSSProperties,
  modalPanelHeading: {
    margin: 0,
    color: "#ffffff",
    fontSize: "1.15rem",
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  modalPanelText: {
    margin: 0,
    color: "rgba(255,255,255,0.82)",
    fontSize: "0.84rem",
    lineHeight: 1.65,
  } satisfies CSSProperties,
  modalPanelLabel: {
    margin: 0,
    color: theme.colors.muted,
    fontSize: "0.84rem",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  modalInfoTitle: {
    margin: 0,
    fontSize: "0.94rem",
    fontWeight: 700,
    lineHeight: 1.25,
    letterSpacing: "-0.01em",
    color: theme.colors.ink,
  } satisfies CSSProperties,
  modalInfoSummary: {
    margin: 0,
    fontSize: "0.84rem",
    lineHeight: 1.6,
    color: theme.colors.muted,
  } satisfies CSSProperties,
  modalInfoChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  } satisfies CSSProperties,
  modalInfoChip: {
    display: "inline-flex",
    alignItems: "center",
    height: "24px",
    padding: "0 9px",
    borderRadius: "6px",
    border: `1px solid rgba(21, 32, 51, 0.11)`,
    background: "#ffffff",
    color: theme.colors.orange,
    fontSize: "0.72rem",
    fontWeight: 700,
  } satisfies CSSProperties,
  modalFooter: {
    padding: "14px 24px 18px",
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    borderTop: border,
  } satisfies CSSProperties,
  modalFooterRow: {
    display: "flex",
    gap: "10px",
    width: "100%",
    justifyContent: "flex-end",
  } satisfies CSSProperties,
  modalFormBody: {
    display: "grid",
    gap: "14px",
  } satisfies CSSProperties,
  modalPrimary: {
    minHeight: "42px",
    padding: "0 20px",
    borderRadius: "12px",
    border: "none",
    background: theme.colors.orange,
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,
  modalSecondary: {
    minHeight: "42px",
    padding: "0 18px",
    borderRadius: "12px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    fontWeight: 600,
    cursor: "pointer",
    fontSize: "0.9rem",
  } satisfies CSSProperties,

  // ── Form elements ──────────────────────────────────────────────────────
  fieldBlock: {
    display: "grid",
    gap: "6px",
    minWidth: 0,
  } satisfies CSSProperties,
  fieldHelp: {
    color: theme.colors.muted,
    fontSize: "0.8rem",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  promptLabel: {
    color: theme.colors.ink,
    fontSize: "0.86rem",
    fontWeight: 700,
    letterSpacing: "-0.005em",
  } satisfies CSSProperties,
  promptInput: {
    minHeight: "40px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "10px 12px",
    resize: "vertical",
    lineHeight: 1.6,
    fontSize: "0.92rem",
    outline: "none",
    width: "100%",
  } satisfies CSSProperties,
  selectInput: {
    minHeight: "42px",
    width: "100%",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "0 12px",
    outline: "none",
    fontSize: "0.9rem",
  } satisfies CSSProperties,
  textInput: {
    minHeight: "42px",
    width: "100%",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "0 12px",
    outline: "none",
    fontSize: "0.9rem",
    minWidth: 0,
  } satisfies CSSProperties,
  compactTextarea: {
    width: "100%",
    minHeight: "56px",
    borderRadius: "8px",
    border,
    background: "#ffffff",
    color: theme.colors.ink,
    padding: "8px 12px",
    resize: "vertical",
    lineHeight: 1.5,
    fontSize: "0.84rem",
    outline: "none",
  } satisfies CSSProperties,
  workflowSummaryText: {
    margin: 0,
    color: theme.colors.muted,
    fontSize: "0.86rem",
    lineHeight: 1.65,
  } satisfies CSSProperties,
  metadataGroup: {
    display: "grid",
    gap: "8px",
    minWidth: 0,
  } satisfies CSSProperties,
  metadataGroupTitle: {
    margin: 0,
    color: theme.colors.ink,
    fontSize: "0.84rem",
    fontWeight: 700,
    letterSpacing: "-0.005em",
  } satisfies CSSProperties,
  metadataItem: {
    display: "grid",
    gap: "6px",
    padding: "10px 12px",
    border,
    borderRadius: "8px",
    background: theme.colors.gray,
    minWidth: 0,
  } satisfies CSSProperties,
  checkboxRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: theme.colors.muted,
    fontSize: "0.82rem",
    fontWeight: 600,
  } satisfies CSSProperties,

  // ── Approval modal ─────────────────────────────────────────────────────
  approvalMessage: {
    margin: 0,
    color: theme.colors.ink,
    fontSize: "0.92rem",
    lineHeight: 1.7,
    padding: "14px 16px",
    background: theme.colors.gray,
    borderRadius: "8px",
    border,
  } satisfies CSSProperties,
  approvalActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  } satisfies CSSProperties,
} as const;
