import type { CSSProperties } from "react";

import { theme } from "../../global/styles";

export const heroStyles = {
  section: {
    position: "relative",
    overflow: "hidden",
    minHeight: "760px",
    padding: "28px 28px 28px",
    background: theme.colors.orange,
    color: "#ffffff",
  } satisfies CSSProperties,
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0",
    width: "min(1180px, 100%)",
    margin: "0 auto",
    position: "relative",
    zIndex: 3,
  } satisfies CSSProperties,
  brand: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0",
  } satisfies CSSProperties,
  logo: {
    width: "172px",
    height: "54px",
    objectFit: "contain",
  } satisfies CSSProperties,
  ctaButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    height: "58px",
    padding: "0 22px",
    border: "2px solid rgba(255, 255, 255, 0.95)",
    borderRadius: "16px",
    background: "transparent",
    color: "#ffffff",
    cursor: "pointer",
    boxShadow: "none",
  } satisfies CSSProperties,
  ctaText: {
    fontFamily: '"Gilroy", "Segoe UI", sans-serif',
    fontSize: "1.08rem",
    fontWeight: 700,
    lineHeight: 1,
  } satisfies CSSProperties,
  ctaIcon: {
    width: "18px",
    height: "18px",
    display: "block",
    flexShrink: 0,
  } satisfies CSSProperties,
  heroBody: {
    width: "min(1440px, 100%)",
    margin: "26px auto 0",
    position: "relative",
    zIndex: 3,
  } satisfies CSSProperties,
  heading: {
    maxWidth: "760px",
    margin: "74px auto 30px",
    textAlign: "center",
    fontSize: "clamp(1.65rem, 2.9vw, 2.65rem)",
    lineHeight: 1.14,
    fontFamily: '"Gilroy", "Segoe UI", sans-serif',
    fontWeight: 500,
  } satisfies CSSProperties,
  aiAccent: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0",
    marginInline: "0.1em",
    position: "relative",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  aiText: {
    color: "#ffffff",
    fontFamily: '"Gilroy", "Segoe UI", sans-serif',
    fontWeight: 500,
    letterSpacing: "-0.02em",
    position: "relative",
    zIndex: 1,
  } satisfies CSSProperties,
  searchRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "16px",
    width: "min(860px, calc(100% - 48px))",
    margin: "0 auto 40px",
  } satisfies CSSProperties,
  searchBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    height: "68px",
    padding: "0 22px",
    borderRadius: "18px",
    background: "#ffffff",
    color: theme.colors.soft,
    boxShadow: theme.shadows.card,
  } satisfies CSSProperties,
  coordinateInput: {
    border: "none",
    outline: "none",
    background: "transparent",
    color: "#3D4152",
    fontSize: "1.02rem",
    fontWeight: 700,
    width: "100%",
  } satisfies CSSProperties,
  searchBoxTextWrap: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
  } satisfies CSSProperties,
  inputText: {
    color: "#7f8696",
    fontSize: "1.02rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  icon: {
    width: "28px",
    height: "28px",
    flexShrink: 0,
    display: "block",
  } satisfies CSSProperties,
  fieldLabel: {
    color: "#7f8696",
    fontSize: "0.88rem",
    fontWeight: 700,
    letterSpacing: "0.01em",
    marginBottom: "2px",
  } satisfies CSSProperties,
  cardsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))",
    gap: "20px",
    width: "min(1400px, 100%)",
    margin: "0 auto",
  } satisfies CSSProperties,
  serviceCardImage: {
    position: "relative",
    width: "100%",
    display: "block",
    borderRadius: "28px",
  } satisfies CSSProperties,
  sideImageLeft: {
    position: "absolute",
    left: "-22px",
    top: "140px",
    width: "min(280px, 22vw)",
    zIndex: 2,
    pointerEvents: "none",
  } satisfies CSSProperties,
  sideImageRight: {
    position: "absolute",
    right: "-12px",
    top: "108px",
    width: "min(290px, 23vw)",
    zIndex: 2,
    pointerEvents: "none",
  } satisfies CSSProperties,
  footerStrip: {
    marginTop: "22px",
    width: "100%",
    padding: "18px 28px",
    background: theme.colors.gray,
    color: theme.colors.muted,
    fontSize: "0.95rem",
    textAlign: "center",
  } satisfies CSSProperties,
  navLink: {
    margin: 0,
    color: "#ffffff",
    fontSize: "1rem",
    fontWeight: 700,
  } satisfies CSSProperties,
} as const;
